version: '3.1'
 
services:
  jupyter-notebook:
   image: jupyter/base-notebook
   container_name: jupyter.local
   ports:
    - "8888:8888"
   volumes:
    - ./work:/home/jovyan/work/
   command: start-notebook.sh --NotebookApp.token=''
  
  mariadb:
   image: mariadb
   container_name: mariadb.lab
   ports:
    - "3306:3306"
   volumes:
    - ./mariadb/data:/data/db/
   environment:
    MYSQL_ROOT_PASSWORD: iii
  adminer:
   image: adminer
   restart: always
   ports:
           -  "8070:8070"
