 version: "3"
 services:
   jupyter-tutorial:
     build: . 
     container_name: m10.jupyter
     user: root
     environment:
       - GRANT_SUDO=yes
     ports:
       - "8888:8888"
       - "5000:5000" 
     command: start-notebook.sh --NotebookApp.token=''
     volumes:
       - ./work:/home/jovyan/work/

   mysql:
     image: mysql:5.7
     container_name: m10.cc104.mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     ports:
       - "3306:3306"
     volumes:
       - ./mysql/data:/data/db/
     environment:
       - MYSQL_ROOT_PASSWORD=iii

   admoner:
     image: adminer
     restart: always
     ports:
       - 8080:8080
